/**
 * questions for typing game - tech stack words
 */
export const techQuestions = [
  { question: 'React', image: './monster1.jpg' },
  { question: 'TypeScript', image: './monster2.jpg' },
  { question: 'Next.js', image: './monster3.jpg' },
  { question: 'Hono', image: './monster4.jpg' },
  { question: 'Tailwind', image: './monster5.jpg' },
  { question: 'JavaScript', image: './monster1.jpg' },
  { question: 'Programming', image: './monster2.jpg' },
  { question: 'Developer', image: './monster3.jpg' },
  { question: 'Algorithm', image: './monster4.jpg' },
  { question: 'Database', image: './monster5.jpg' },
  { question: 'Frontend', image: './monster1.jpg' },
  { question: 'Backend', image: './monster2.jpg' },
  { question: 'Fullstack', image: './monster3.jpg' },
  { question: 'Framework', image: './monster4.jpg' },
  { question: 'Interface', image: './monster5.jpg' },
  { question: 'Vue.js', image: './monster1.jpg' },
  { question: 'Angular', image: './monster2.jpg' },
  { question: 'Express', image: './monster3.jpg' },
  { question: 'MongoDB', image: './monster4.jpg' },
  { question: 'PostgreSQL', image: './monster5.jpg' },
  { question: 'Docker', image: './monster1.jpg' },
  { question: 'Kubernetes', image: './monster2.jpg' },
  { question: 'GraphQL', image: './monster3.jpg' },
  { question: 'Redux', image: './monster4.jpg' },
  { question: 'Node.js', image: './monster5.jpg' },
  { question: 'Python', image: './monster1.jpg' },
  { question: 'Django', image: './monster2.jpg' },
  { question: 'FastAPI', image: './monster3.jpg' },
  { question: 'AWS', image: './monster4.jpg' },
  { question: 'Firebase', image: './monster5.jpg' },
  { question: 'Rust', image: './monster1.jpg' },
  { question: 'Go', image: './monster2.jpg' },
  { question: 'Swift', image: './monster3.jpg' },
  { question: 'Kotlin', image: './monster4.jpg' },
  { question: 'Java', image: './monster5.jpg' },
  { question: 'Spring', image: './monster1.jpg' },
  { question: 'Ruby', image: './monster2.jpg' },
  { question: 'Rails', image: './monster3.jpg' },
  { question: 'Redis', image: './monster4.jpg' },
  { question: 'MySQL', image: './monster5.jpg' },
  { question: 'Svelte', image: './monster1.jpg' },
  { question: 'Astro', image: './monster2.jpg' },
  { question: 'Vite', image: './monster3.jpg' },
  { question: 'Webpack', image: './monster4.jpg' },
  { question: 'ESLint', image: './monster5.jpg' },
  { question: 'Jest', image: './monster1.jpg' },
  { question: 'Cypress', image: './monster2.jpg' },
  { question: 'Remix', image: './monster3.jpg' },
  { question: 'Prisma', image: './monster4.jpg' },
  { question: 'Vercel', image: './monster5.jpg' },
];

/**
 * questions for typing game - tailwind css classnames
 */
export const tailwindQuestions = [
  { question: 'flex', image: './monster1.jpg' },
  { question: 'grid', image: './monster2.jpg' },
  { question: 'container', image: './monster3.jpg' },
  { question: 'mx-auto', image: './monster4.jpg' },
  { question: 'py-4', image: './monster5.jpg' },
  { question: 'px-6', image: './monster1.jpg' },
  { question: 'text-center', image: './monster2.jpg' },
  { question: 'font-bold', image: './monster3.jpg' },
  { question: 'text-xl', image: './monster4.jpg' },
  { question: 'bg-blue-500', image: './monster5.jpg' },
  { question: 'text-white', image: './monster1.jpg' },
  { question: 'rounded-lg', image: './monster2.jpg' },
  { question: 'shadow-md', image: './monster3.jpg' },
  { question: 'hover:bg-blue-700', image: './monster4.jpg' },
  { question: 'focus:outline-none', image: './monster5.jpg' },
  { question: 'transition', image: './monster1.jpg' },
  { question: 'duration-300', image: './monster2.jpg' },
  { question: 'transform', image: './monster3.jpg' },
  { question: 'hover:scale-105', image: './monster4.jpg' },
  { question: 'justify-between', image: './monster5.jpg' },
  { question: 'items-center', image: './monster1.jpg' },
  { question: 'gap-4', image: './monster2.jpg' },
  { question: 'w-full', image: './monster3.jpg' },
  { question: 'h-screen', image: './monster4.jpg' },
  { question: 'max-w-md', image: './monster5.jpg' },
  { question: 'border-2', image: './monster1.jpg' },
  { question: 'border-gray-300', image: './monster2.jpg' },
  { question: 'p-4', image: './monster3.jpg' },
  { question: 'mt-4', image: './monster4.jpg' },
  { question: 'mb-6', image: './monster5.jpg' },
  { question: 'hidden', image: './monster1.jpg' },
  { question: 'md:block', image: './monster2.jpg' },
  { question: 'lg:flex', image: './monster3.jpg' },
  { question: 'sm:grid', image: './monster4.jpg' },
  { question: 'overflow-hidden', image: './monster5.jpg' },
  { question: 'opacity-75', image: './monster1.jpg' },
  { question: 'cursor-pointer', image: './monster2.jpg' },
  { question: 'z-10', image: './monster3.jpg' },
  { question: 'absolute', image: './monster4.jpg' },
  { question: 'relative', image: './monster5.jpg' },
  { question: 'inset-0', image: './monster1.jpg' },
  { question: 'object-cover', image: './monster2.jpg' },
  { question: 'object-center', image: './monster3.jpg' },
  { question: 'filter', image: './monster4.jpg' },
  { question: 'blur-sm', image: './monster5.jpg' },
  { question: 'grayscale', image: './monster1.jpg' },
  { question: 'dark:bg-gray-800', image: './monster2.jpg' },
  { question: 'dark:text-white', image: './monster3.jpg' },
  { question: 'animate-pulse', image: './monster4.jpg' },
  { question: 'animate-spin', image: './monster5.jpg' },
];

/**
 * questions for typing game - material ui components
 */
export const materialQuestions = [
  { question: 'Accordion', image: './mui-real/accordion.png' },
  { question: 'Alert', image: './mui-real/alert.png' },
  { question: 'AppBar', image: './mui-real/app-bar.png' },
  { question: 'Avatar', image: './mui-real/avatar.png' },
  { question: 'Badge', image: './mui-real/badge.png' },
  { question: 'Button', image: './mui-real/button.png' },
  { question: 'Card', image: './mui-real/card.png' },
  { question: 'Checkbox', image: './mui-real/checkbox.png' },
  { question: 'Chip', image: './mui-real/chip.png' },
  { question: 'Dialog', image: './mui-real/dialog.png' },
  { question: 'Divider', image: './mui-real/divider.png' },
  { question: 'Drawer', image: './mui-real/drawer.png' },
  { question: 'Fab', image: './mui-real/fab.png' },
  { question: 'Grid', image: './mui-real/grid.png' },
  { question: 'Icon', image: './mui-real/icon.png' },
  { question: 'IconButton', image: './mui-real/icon-button.png' },
  { question: 'LinearProgress', image: './mui-real/linear-progress.png' },
  { question: 'Link', image: './mui-real/link.png' },
  { question: 'List', image: './mui-real/list.png' },
  { question: 'Menu', image: './mui-real/menu.png' },
  { question: 'Modal', image: './mui-real/modal.png' },
  { question: 'Paper', image: './mui-real/paper.png' },
  { question: 'Popover', image: './mui-real/popover.png' },
  { question: 'Progress', image: './mui-real/progress.png' },
  { question: 'Radio', image: './mui-real/radio.png' },
  { question: 'Rating', image: './mui-real/rating.png' },
  { question: 'Select', image: './mui-real/select.png' },
  { question: 'Skeleton', image: './mui-real/skeleton.png' },
  { question: 'Slider', image: './mui-real/slider.png' },
  { question: 'Snackbar', image: './mui-real/snackbar.png' },
  { question: 'SpeedDial', image: './mui-real/speed-dial.png' },
  { question: 'Stepper', image: './mui-real/stepper.png' },
  { question: 'Switch', image: './mui-real/switch.png' },
  { question: 'Table', image: './mui-real/table.png' },
  { question: 'Tabs', image: './mui-real/tabs.png' },
  { question: 'TextField', image: './mui-real/text-field.png' },
  { question: 'Timeline', image: './mui-real/timeline.png' },
  { question: 'ToggleButton', image: './mui-real/toggle-button.png' },
  { question: 'Toolbar', image: './mui-real/toolbar.png' },
  { question: 'Tooltip', image: './mui-real/tooltip.png' },
  { question: 'Typography', image: './mui-real/typography.png' },
  { question: 'Breadcrumbs', image: './mui-real/breadcrumbs.png' },
  { question: 'ButtonGroup', image: './mui-real/button-group.png' },
  { question: 'Container', image: './mui-real/container.png' },
  { question: 'FormControl', image: './mui-real/form-control.png' },
  { question: 'InputLabel', image: './mui-real/input-label.png' },
  { question: 'Pagination', image: './mui-real/pagination.png' },
  { question: 'Stack', image: './mui-real/stack.png' },
  { question: 'TreeView', image: './mui-real/tree-view.png' },
];

export const questions = techQuestions;
