/**
 * questions for typing game - tech stack words
 */
export const techQuestions = [
  { question: 'React', image: './monster1.jpg' },
  { question: 'TypeScript', image: './monster2.jpg' },
  { question: 'Next.js', image: './monster3.jpg' },
  { question: 'Hono', image: './monster4.jpg' },
  { question: 'Tailwind', image: './monster5.jpg' },
  { question: 'JavaScript', image: './monster1.jpg' },
  { question: 'Programming', image: './monster2.jpg' },
  { question: 'Developer', image: './monster3.jpg' },
  { question: 'Algorithm', image: './monster4.jpg' },
  { question: 'Database', image: './monster5.jpg' },
  { question: 'Frontend', image: './monster1.jpg' },
  { question: 'Backend', image: './monster2.jpg' },
  { question: 'Fullstack', image: './monster3.jpg' },
  { question: 'Framework', image: './monster4.jpg' },
  { question: 'Interface', image: './monster5.jpg' },
  { question: 'Vue.js', image: './monster1.jpg' },
  { question: 'Angular', image: './monster2.jpg' },
  { question: 'Express', image: './monster3.jpg' },
  { question: 'MongoDB', image: './monster4.jpg' },
  { question: 'PostgreSQL', image: './monster5.jpg' },
  { question: 'Docker', image: './monster1.jpg' },
  { question: 'Kubernetes', image: './monster2.jpg' },
  { question: 'GraphQL', image: './monster3.jpg' },
  { question: 'Redux', image: './monster4.jpg' },
  { question: 'Node.js', image: './monster5.jpg' },
  { question: 'Python', image: './monster1.jpg' },
  { question: 'Django', image: './monster2.jpg' },
  { question: 'FastAPI', image: './monster3.jpg' },
  { question: 'AWS', image: './monster4.jpg' },
  { question: 'Firebase', image: './monster5.jpg' },
  { question: 'Rust', image: './monster1.jpg' },
  { question: 'Go', image: './monster2.jpg' },
  { question: 'Swift', image: './monster3.jpg' },
  { question: 'Kotlin', image: './monster4.jpg' },
  { question: 'Java', image: './monster5.jpg' },
  { question: 'Spring', image: './monster1.jpg' },
  { question: 'Ruby', image: './monster2.jpg' },
  { question: 'Rails', image: './monster3.jpg' },
  { question: 'Redis', image: './monster4.jpg' },
  { question: 'MySQL', image: './monster5.jpg' },
  { question: 'Svelte', image: './monster1.jpg' },
  { question: 'Astro', image: './monster2.jpg' },
  { question: 'Vite', image: './monster3.jpg' },
  { question: 'Webpack', image: './monster4.jpg' },
  { question: 'ESLint', image: './monster5.jpg' },
  { question: 'Jest', image: './monster1.jpg' },
  { question: 'Cypress', image: './monster2.jpg' },
  { question: 'Remix', image: './monster3.jpg' },
  { question: 'Prisma', image: './monster4.jpg' },
  { question: 'Vercel', image: './monster5.jpg' },
];

/**
 * questions for typing game - tailwind css classnames
 */
export const tailwindQuestions = [
  { question: 'flex', image: './monster1.jpg' },
  { question: 'grid', image: './monster2.jpg' },
  { question: 'container', image: './monster3.jpg' },
  { question: 'mx-auto', image: './monster4.jpg' },
  { question: 'py-4', image: './monster5.jpg' },
  { question: 'px-6', image: './monster1.jpg' },
  { question: 'text-center', image: './monster2.jpg' },
  { question: 'font-bold', image: './monster3.jpg' },
  { question: 'text-xl', image: './monster4.jpg' },
  { question: 'bg-blue-500', image: './monster5.jpg' },
  { question: 'text-white', image: './monster1.jpg' },
  { question: 'rounded-lg', image: './monster2.jpg' },
  { question: 'shadow-md', image: './monster3.jpg' },
  { question: 'hover:bg-blue-700', image: './monster4.jpg' },
  { question: 'focus:outline-none', image: './monster5.jpg' },
  { question: 'transition', image: './monster1.jpg' },
  { question: 'duration-300', image: './monster2.jpg' },
  { question: 'transform', image: './monster3.jpg' },
  { question: 'hover:scale-105', image: './monster4.jpg' },
  { question: 'justify-between', image: './monster5.jpg' },
  { question: 'items-center', image: './monster1.jpg' },
  { question: 'gap-4', image: './monster2.jpg' },
  { question: 'w-full', image: './monster3.jpg' },
  { question: 'h-screen', image: './monster4.jpg' },
  { question: 'max-w-md', image: './monster5.jpg' },
  { question: 'border-2', image: './monster1.jpg' },
  { question: 'border-gray-300', image: './monster2.jpg' },
  { question: 'p-4', image: './monster3.jpg' },
  { question: 'mt-4', image: './monster4.jpg' },
  { question: 'mb-6', image: './monster5.jpg' },
  { question: 'hidden', image: './monster1.jpg' },
  { question: 'md:block', image: './monster2.jpg' },
  { question: 'lg:flex', image: './monster3.jpg' },
  { question: 'sm:grid', image: './monster4.jpg' },
  { question: 'overflow-hidden', image: './monster5.jpg' },
  { question: 'opacity-75', image: './monster1.jpg' },
  { question: 'cursor-pointer', image: './monster2.jpg' },
  { question: 'z-10', image: './monster3.jpg' },
  { question: 'absolute', image: './monster4.jpg' },
  { question: 'relative', image: './monster5.jpg' },
  { question: 'inset-0', image: './monster1.jpg' },
  { question: 'object-cover', image: './monster2.jpg' },
  { question: 'object-center', image: './monster3.jpg' },
  { question: 'filter', image: './monster4.jpg' },
  { question: 'blur-sm', image: './monster5.jpg' },
  { question: 'grayscale', image: './monster1.jpg' },
  { question: 'dark:bg-gray-800', image: './monster2.jpg' },
  { question: 'dark:text-white', image: './monster3.jpg' },
  { question: 'animate-pulse', image: './monster4.jpg' },
  { question: 'animate-spin', image: './monster5.jpg' },
];

/**
 * questions for typing game - material ui components
 */
export const materialQuestions = [
  { question: 'Accordion', image: './mui/accordion.jpg' },
  { question: 'Alert', image: './mui/alert.jpg' },
  { question: 'AppBar', image: './mui/appbar.jpg' },
  { question: 'Avatar', image: './mui/avatar.jpg' },
  { question: 'Badge', image: './mui/badge.jpg' },
  { question: 'Button', image: './mui/button.jpg' },
  { question: 'Card', image: './mui/card.jpg' },
  { question: 'Checkbox', image: './mui/checkbox.jpg' },
  { question: 'Chip', image: './mui/chip.jpg' },
  { question: 'Dialog', image: './mui/dialog.jpg' },
  { question: 'Divider', image: './mui/divider.jpg' },
  { question: 'Drawer', image: './mui/drawer.jpg' },
  { question: 'Fab', image: './mui/fab.jpg' },
  { question: 'Grid', image: './mui/grid.jpg' },
  { question: 'Icon', image: './mui/icon.jpg' },
  { question: 'IconButton', image: './mui/iconbutton.jpg' },
  { question: 'LinearProgress', image: './mui/linearprogress.jpg' },
  { question: 'Link', image: './mui/link.jpg' },
  { question: 'List', image: './mui/list.jpg' },
  { question: 'Menu', image: './mui/menu.jpg' },
  { question: 'Modal', image: './mui/modal.jpg' },
  { question: 'Paper', image: './mui/paper.jpg' },
  { question: 'Popover', image: './mui/popover.jpg' },
  { question: 'Progress', image: './mui/progress.jpg' },
  { question: 'Radio', image: './mui/radio.jpg' },
  { question: 'Rating', image: './mui/rating.jpg' },
  { question: 'Select', image: './mui/select.jpg' },
  { question: 'Skeleton', image: './mui/skeleton.jpg' },
  { question: 'Slider', image: './mui/slider.jpg' },
  { question: 'Snackbar', image: './mui/snackbar.jpg' },
  { question: 'SpeedDial', image: './mui/speeddial.jpg' },
  { question: 'Stepper', image: './mui/stepper.jpg' },
  { question: 'Switch', image: './mui/switch.jpg' },
  { question: 'Table', image: './mui/table.jpg' },
  { question: 'Tabs', image: './mui/tabs.jpg' },
  { question: 'TextField', image: './mui/textfield.jpg' },
  { question: 'Timeline', image: './mui/timeline.jpg' },
  { question: 'ToggleButton', image: './mui/togglebutton.jpg' },
  { question: 'Toolbar', image: './mui/toolbar.jpg' },
  { question: 'Tooltip', image: './mui/tooltip.jpg' },
  { question: 'Typography', image: './mui/typography.jpg' },
  { question: 'Breadcrumbs', image: './mui/breadcrumbs.jpg' },
  { question: 'ButtonGroup', image: './mui/buttongroup.jpg' },
  { question: 'Container', image: './mui/container.jpg' },
  { question: 'FormControl', image: './mui/formcontrol.jpg' },
  { question: 'InputLabel', image: './mui/inputlabel.jpg' },
  { question: 'Pagination', image: './mui/pagination.jpg' },
  { question: 'Stack', image: './mui/stack.jpg' },
  { question: 'TreeView', image: './mui/treeview.jpg' },
];

export const questions = techQuestions;
