/**
 * questions for typing game - tech stack words
 */
export const questions = [
    { question: 'React', image: './monster1.jpg' },
    { question: 'TypeScript', image: './monster2.jpg' },
    { question: 'Next.js', image: './monster3.jpg' },
    { question: 'Hono', image: './monster4.jpg' },
    { question: 'Tailwind', image: './monster5.jpg' },
    { question: 'JavaScript', image: './monster1.jpg' },
    { question: 'Programming', image: './monster2.jpg' },
    { question: 'Developer', image: './monster3.jpg' },
    { question: 'Algorithm', image: './monster4.jpg' },
    { question: 'Database', image: './monster5.jpg' },
    { question: 'Frontend', image: './monster1.jpg' },
    { question: 'Backend', image: './monster2.jpg' },
    { question: 'Fullstack', image: './monster3.jpg' },
    { question: 'Framework', image: './monster4.jpg' },
    { question: 'Interface', image: './monster5.jpg' },
    { question: 'Vue.js', image: './monster1.jpg' },
    { question: 'Angular', image: './monster2.jpg' },
    { question: 'Express', image: './monster3.jpg' },
    { question: 'MongoDB', image: './monster4.jpg' },
    { question: 'PostgreSQL', image: './monster5.jpg' },
    { question: 'Docker', image: './monster1.jpg' },
    { question: 'Kubernetes', image: './monster2.jpg' },
    { question: 'GraphQL', image: './monster3.jpg' },
    { question: 'Redux', image: './monster4.jpg' },
    { question: 'Node.js', image: './monster5.jpg' },
    { question: 'Python', image: './monster1.jpg' },
    { question: 'Django', image: './monster2.jpg' },
    { question: 'FastAPI', image: './monster3.jpg' },
    { question: 'AWS', image: './monster4.jpg' },
    { question: 'Firebase', image: './monster5.jpg' },
    { question: 'Rust', image: './monster1.jpg' },
    { question: 'Go', image: './monster2.jpg' },
    { question: 'Swift', image: './monster3.jpg' },
    { question: 'Kotlin', image: './monster4.jpg' },
    { question: 'Java', image: './monster5.jpg' },
    { question: 'Spring', image: './monster1.jpg' },
    { question: 'Ruby', image: './monster2.jpg' },
    { question: 'Rails', image: './monster3.jpg' },
    { question: 'Redis', image: './monster4.jpg' },
    { question: 'MySQL', image: './monster5.jpg' },
    { question: 'Svelte', image: './monster1.jpg' },
    { question: 'Astro', image: './monster2.jpg' },
    { question: 'Vite', image: './monster3.jpg' },
    { question: 'Webpack', image: './monster4.jpg' },
    { question: 'ESLint', image: './monster5.jpg' },
    { question: 'Jest', image: './monster1.jpg' },
    { question: 'Cypress', image: './monster2.jpg' },
    { question: 'Remix', image: './monster3.jpg' },
    { question: 'Prisma', image: './monster4.jpg' },
    { question: 'Vercel', image: './monster5.jpg' }
];